---
- hosts: services_machine

  remote_user: "{{ remote_user_id }}"
  become: true
  
  tasks:
     - name: Create application {{ application.name }} folder if not existing
       file: 
           path={{ install_apps_folder }}/{{ application.name }}
           state=directory 
           owner={{ remote_user_id }} 
           group={{ remote_user_id }} 
           recurse=yes
       with_items: 
        - "{{ application }}"
       
     - name: Deploying {{ application.name }}
       unarchive: 
           src={{ artifactory_repo_url }}/{{application.package}} 
           dest={{ install_apps_folder }}/{{ application.name }}
           remote_src=yes
       with_items: "{{ application }}"
     
     - name: Configuring application {{ application.name }} port
       lineinfile: 
            dest={{ install_apps_folder }}/{{ application.name }}/conf/application.properties 
            regexp='^.*server\.port.*$' 
            line='server.port={{ application.port }}' 
            owner={{ remote_user_id }} group={{ remote_user_id }}
       with_items: "{{ application }}"
