---
- hosts: services_machine

  remote_user: "{{ remote_user_id }}"
  become: true
  
  tasks:
     - name: Create applications folder if not existing
       file: 
           path={{ install_apps_folder }}/{{ item.name }}
           state=directory 
           owner={{ remote_user_id }} 
           group={{ remote_user_id }} 
           recurse=yes
       with_items: "{{ applicationsEsiee }}"
       
     - name: Deploying applications
       unarchive: 
           src={{ artifactory_repo_url }}/{{item.package}} 
           dest={{ install_apps_folder }}/{{ item.name }}
           remote_src=yes
       with_items: "{{ applicationsEsiee }}"
     
     - name: Configuring applications port
       lineinfile: 
            dest={{ install_apps_folder }}/{{ item.name }}/conf/application.properties 
            regexp='^.*server\.port.*$' 
            line='server.port={{ item.port }}' 
            owner={{ remote_user_id }} group={{ remote_user_id }}
       with_items: "{{ applicationsEsiee }}"
