---
- hosts: services_machine

  remote_user: "{{ remote_user_id }}"
  become: true
  
  tasks:
     - name: Create application {{ artefact_name }} folder if not existing
       file: 
           path={{ apps_folder }}/{{ artefact_name }}
           state=directory 
           owner={{ remote_user_id }} 
           group={{ remote_user_id }} 
           recurse=yes
       
     - name: Deploying {{ artefact_name }}
       unarchive: 
           src={{ artifactory_repo_url }}/{{artefact_path}} 
           dest={{ apps_folder }}/{{ artefact_name }}
           remote_src=yes
     
     - name: Configuring application {{ artefact_name }} port
       lineinfile: 
            dest={{ apps_folder }}/{{ artefact_name }}/conf/application.properties 
            regexp='^.*server\.port.*$' 
            line='server.port={{ rest_api_server_port }}' 
            owner={{ remote_user_id }} group={{ remote_user_id }}
