- name: updating machine
  apt: update_cache=yes

- name: installing dependencies
  apt: pkg={{ item }} state=installed update-cache=yes
  with_items:
  - python-software-properties
  - curl
  - libssl0.9.8
  - libjna-java
  - sysstat
  
